### ISSUE TITLE
Night mode just on home

### ISSUE THREAD

**Issue by exodius48** [BrianValente/WAMOD#12]
When i select conversation or chat with someone in dark mode, the background become white, not dark.

**Comment by BrianValente** [comment]
So, it's not "just on home". That's because Night mode won't change your chat custom background.

**Comment by exodius48** [comment]
i'm using original background, not custom. so it's imposible to make chat background follow night mode?

**Comment by zamzameir** [comment]
then just set custom background color? isit that hard? hmm
its #303030 btw

**Comment by exodius48** [comment]
I don't know about hex string. :D
