### ISSUE TITLE
Chat backups

### ISSUE THREAD

**Issue by sandymanu** [BrianValente/WAMOD#14]
The chat backup taken via wamod (rc3) doesn't work with official playstore release or the latest apk via Whatsapp official website. It fails to detect the chat backup.

The chat backup created by wamod is crypt11 and that isn't detected by either latest apk in Whatsapp site or the playstore base. Only wamod is able to detect the chat backups.

This makes it unusable with original Whatsapp or any other mods which are based on latest playstore base or official website apk.

**Comment by BrianValente** [comment]
Are backups compatible between other mods and stock WhatsApp? Maybe is a problem with the signature.
Use Titanium Backup as workaround.

**Comment by sandymanu** [comment]
My existing chat backup is important for me and hence struck with wamod itself. But I can assure u that it works between other mods and official (at least that's what I see in comments of other mods )

Also had been banned for verification for 48 hours due to too much clean installs to verify this backup issue. I was trying official Whatsapp, playstore Whatsapp,other mods based on latest base and since all failed to detect I can't do one more clean install for a  while.

I will use titanium for now which is not an issue. But the issue is resolvable one.Right ?

**Comment by BrianValente** [comment]
To be honest I don't care about backups if SMS verification works. Just use Titanium Backup for now. I don't know why backup restore doesn't work and I don't have time to check why, probably the files are encrypted, WhatsApp is implementing more security.
