### ISSUE TITLE
Sending audio files ( via picker/share button)

### ISSUE THREAD

**Issue by Angel203** [BrianValente/WAMOD#15]
During the sending process (about the half) it changes the duration ×3 and when i play the file, it sounds very strange.

**Comment by BrianValente** [comment]
Works fine for me. Also, that's not a WAMOD problem, try with stock 2.16.21 and comment the results.

**Comment by Angel203** [comment]
Thanks for  your answer.
This has to be a WhatsApp related issue.
Every "audio/mp4" in a ".3gp" File, recorded by the standard LG G4 voice recording app, ended in such a "bad remix".
All normal audio files are working fine with both apps, stock and your mod :)
