### ISSUE TITLE
Notification problem

### ISSUE THREAD

**Issue by bagi00** [BrianValente/WAMOD#17]
I can't tick/untick the "in notification tones" options. It simply does nothing when i press it.

**Comment by BrianValente** [comment]
Android version? On Android N works fine.

**Comment by bagi00** [comment]
Marshmallow. I don't know why...it seems whatsapp process isn't active in
background. I think it's a ROM issue.

Il sab 23 apr 2016, 19:24 Brian Valente <notifications@github.com> ha
scritto:

**Comment by ilkercnsy** [comment]
Same for me, OS 6.0.1

**Comment by ilkercnsy** [comment]
Edit: New update fixed the issues. Thanks

**Comment by BrianValente** [comment]
Fixed 👍🏻
