### ISSUE TITLE
something wrong with 'clear all chat'

### ISSUE THREAD

**Issue by exodius48** [BrianValente/WAMOD#55]
its not fully working on 1.3.2.
try to open chat then tap three dots on right corner. select other > clear chat
wamod closes automatically like force close, then open itself

also when i selec options, background too dark

**Comment by BrianValente** [comment]
Works fine on 1.3.3

**Comment by exodius48** [comment]
@BrianValente where to get 1.3.3? i don't get any update till now

**Comment by BrianValente** [comment]
https://plus.google.com/112214787896843863316/posts/JvqHYXdouTJ
