### ISSUE TITLE
i always can't send message after wamod update

### ISSUE THREAD

**Issue by exodius48** [BrianValente/WAMOD#69]
actually i get this error when i update from 1.3.2 to 1.3.3 , i can't send message , always show timed clock. then i reinstall wamod.
but this bug appear when i update to 1.3.4 from 1.3.3. i can't send message again. so i mark it as bug, can't send message after wamod update.
but i can receive message from group / contact

**Comment by zamzameir** [comment]
restore default privacy config

**Comment by exodius48** [comment]
I uninstalled & installed again, now working.
