### ISSUE TITLE
Any development progress?

### ISSUE THREAD

**Issue by exodius48** [BrianValente/WAMOD#73]
You promise next year on this https://github.com/BrianValente/WAMOD/issues/72

**Comment by BrianValente** [comment]
This project has been closed permanently. I'm sorry. [https://plus.google.com/u/0/112214787896843863316/posts/D12uCBJGjHK](url)

**Comment by exodius48** [comment]
Oh no.. :( 
Sad to hear that, but thanks for develop WAMOD. 
I wish the best for you. Good luck for your next project. :)
